language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -e .[dev]
  - pip install coveralls
# command to run tests
script:
  - pytest
  - coverage run --source=src pytest
after_success:
  - coveralls